### ISSUE TITLE
Error serving app on localhost 

### ISSUE THREAD

**Issue by archer747** [2sic/dnn-sxc-angular#4]
Hi,

I wanted to give this a try and ran into the following error:

ERROR in node_modules/@2sic.com/dnn-sxc-angular/dist/context/context.service.d.ts(22,32): error TS2304: Cannot find name 'SxcController'.

Do we need to have the 2Sxc App/Content module installed as well?

Thanks
Mark

**Comment by iJungleboy** [comment]
to run it on localhost (for dev-mode) you have to do some things to "fake" a DNN and 2sxc, because otherwise webapi endpoints will not give you the data you want. We haven't fully worked it out yet, and got delayed because of problems with angular5 and AOT.

It's all prepared, but we had some trouble migrating to angular5 in December, so the current version isn't stable ATM and I wouldn't want to send you down a path of trial and error, just to see that it doesn't work right. 

If you use an older release from ca. October you should be good to go, but the latest isn't stable. 

So your best call is to use either the older version on angular4, or use the latest using angular5 and only run it inside DNN - and not using `-prod` build yet, because of the AOT.

**Comment by iJungleboy** [comment]
Note: we finished/enhanced this - it works now :)
